from enums.currency import CURRENCY
from enums.currency_pair import CURRENCY_PAIR

SECONDS_IN_WEEK = 604800
SECONDS_IN_DAY = 86400

HTTP_TIMEOUT_SECONDS = 25

ZERO_BALANCE = 0.0

ARBITRAGE_CURRENCY = [CURRENCY.BITCOIN, CURRENCY.DASH, CURRENCY.BCC, CURRENCY.XRP, CURRENCY.LTC, CURRENCY.ETC,
                      CURRENCY.ETH]

ARBITRAGE_PAIRS = [CURRENCY_PAIR.BTC_TO_DASH, CURRENCY_PAIR.BTC_TO_BCC, CURRENCY_PAIR.BTC_TO_XRP,
                   CURRENCY_PAIR.BTC_TO_LTC, CURRENCY_PAIR.BTC_TO_ETC, CURRENCY_PAIR.BTC_TO_ETH]