import multiprocessing

from decimal import Decimal
from enums.currency import CURRENCY
from enums.currency_pair import CURRENCY_PAIR

SECONDS_IN_WEEK = 604800
SECONDS_IN_DAY = 86400

HTTP_TIMEOUT_SECONDS = 25
HTTP_TIMEOUT_ORDER_BOOK_ARBITRAGE = 3
DEAL_MAX_TIMEOUT = 10

HTTP_SUCCESS = 200

ZERO_BALANCE = 0.0
ARBITRAGE_CURRENCY = CURRENCY.values()
ARBITRAGE_PAIRS = CURRENCY_PAIR.values()

BASE_CURRENCY = [CURRENCY.BITCOIN, CURRENCY.ETH, CURRENCY.USDT]

# FIXME NOTE read it from settings
BITCOIN_ALARM_THRESHOLD = 0.1
ETHERIUM_ALARM_THRESHOLD = 1.0
USDT_ALARM_THRESHOLD = 1000.0
BASE_CURRENCIES_BALANCE_THRESHOLD = {
    CURRENCY.BITCOIN: BITCOIN_ALARM_THRESHOLD,
    CURRENCY.ETH: ETHERIUM_ALARM_THRESHOLD,
    CURRENCY.USDT: USDT_ALARM_THRESHOLD
}

MIN_VOLUME_COEFFICIENT = {
    CURRENCY.BITCOIN: Decimal(0.004),
    CURRENCY.ETH: Decimal(0.04),
    CURRENCY.USDT: Decimal(40)
}

MAX_VOLUME_COEFFICIENT = Decimal(0.9)

CACHE_HOST = "54.193.19.230"
CACHE_PORT = 6379

CORE_NUM = multiprocessing.cpu_count()
POOL_SIZE = 8 * CORE_NUM

# FIXME NOTE: arbitrage_core
# This is indexes for comparison bid\ask within order books
# yeap, global constants is very bad
FIRST = 0
LAST = 0

BALANCE_EXPIRED_THRESHOLD = 60
MIN_CAP_UPDATE_TIMEOUT = 900
BALANCE_UPDATE_TIMEOUT = 1
NO_MAX_CAP_LIMIT = 0
NO_MIN_CAP_LIMIT = 0

DECIMAL_ZERO = Decimal(0.0)

START_OF_TIME = -1

FLOAT_POINT_PRECISION = Decimal("0.00000001")
MAX_VOLUME_ORDER_BOOK = 0.00001

HEARTBEAT_TIMEOUT = 60

API_KEY_PATH = "./secret_keys"

DB_HOST = "orders.cervsj06c8zw.us-west-1.rds.amazonaws.com"
DB_PORT = 5432
DB_NAME = "crypto"
