from enums.deploy_units import DEPLOY_UNIT
from deploy.DeployUnit import DeployUnit

# pypy is option as well. NOTE: it can be 2x-3x faster
PYTHON_INTERPETATOR = "python"

FULL_COMMAND = PYTHON_INTERPETATOR + " arbitrage_between_pair.py"

BALANCE_SCREEN_NAME = "Balance_Retrieval"
BALANCE_WINDOW_NAME = "balance_update"
BALANCE_UPDATE_COMMAND = PYTHON_INTERPETATOR + " -m services.balance_monitoring"
BALANCE_UPDATE_DEPLOY_UNIT = DeployUnit(BALANCE_SCREEN_NAME, BALANCE_WINDOW_NAME, BALANCE_UPDATE_COMMAND)

COMMON_SCREEN_NAME = "crypto"

ARBITRAGE_NOTIFIER_SCREEN_NAME = COMMON_SCREEN_NAME
ARBITRAGE_NOTIFIER_WINDOW_NAME = "arbitrage_notifier"
ARBITRAGE_NOTIFIER_COMMAND = PYTHON_INTERPETATOR + " -m services.arbitrage_monitoring"
ARBITRAGE_NOTIFIER_DEPLOY_UNIT = DeployUnit(ARBITRAGE_NOTIFIER_SCREEN_NAME, ARBITRAGE_NOTIFIER_WINDOW_NAME,
                                            ARBITRAGE_NOTIFIER_COMMAND)

ORDER_BOOK_RETRIEVAL_SCREEN_NAME = COMMON_SCREEN_NAME
ORDER_BOOK_RETRIEVAL_WINDOW_NAME = "balance_update"
ORDER_BOOK_RETRIEVAL_COMMAND = PYTHON_INTERPETATOR + " -m services.order_book_retrieval"
ORDER_BOOK_RETRIEVAL_DEPLOY_UNIT = DeployUnit(ORDER_BOOK_RETRIEVAL_SCREEN_NAME, ORDER_BOOK_RETRIEVAL_WINDOW_NAME,
                                              ORDER_BOOK_RETRIEVAL_COMMAND)

HISTORY_RETRIEVAL_SCREEN_NAME = COMMON_SCREEN_NAME
HISTORY_RETRIEVAL_WINDOW_NAME = "balance_update"
HISTORY_RETRIEVAL_COMMAND = PYTHON_INTERPETATOR + " -m services.history_retrieval"
HISTORY_RETRIEVAL_DEPLOY_UNIT = DeployUnit(HISTORY_RETRIEVAL_SCREEN_NAME, HISTORY_RETRIEVAL_WINDOW_NAME,
                                           HISTORY_RETRIEVAL_COMMAND)

TELEGRAM_NOTIFIER_SCREEN_NAME = COMMON_SCREEN_NAME
TELEGRAM_NOTIFIER_WINDOW_NAME = "telegram_notifier"
TELEGRAM_NOTIFIER_COMMAND = PYTHON_INTERPETATOR + " -m services.telegram_notifier"
TELEGRAM_NOTIFIER_DEPLOY_UNIT = DeployUnit(TELEGRAM_NOTIFIER_SCREEN_NAME, TELEGRAM_NOTIFIER_WINDOW_NAME,
                                           TELEGRAM_NOTIFIER_COMMAND)


DATA_RETRIEVAL_SERVICES = {
    DEPLOY_UNIT.BALANCE_MONITORING: BALANCE_UPDATE_DEPLOY_UNIT,
    DEPLOY_UNIT.ARBITRAGE_NOTIFIER: ARBITRAGE_NOTIFIER_DEPLOY_UNIT,
    DEPLOY_UNIT.ORDER_BOOK: ORDER_BOOK_RETRIEVAL_DEPLOY_UNIT,
    DEPLOY_UNIT.ORDER_HISTORY: HISTORY_RETRIEVAL_DEPLOY_UNIT,
}