from binance.currency_utils import get_currency_pair_to_binance
from utils.currency_utils import split_currency_pairs
from utils.string_utils import truncate_float
from enums.currency import CURRENCY


PRECISIONS_BTC = {
    "ETHBTC":  0.001,
    "LTCBTC":  0.01,
    "BNBBTC":  1,
    "NEOBTC":  0.01,
    "GASBTC":  0.01,
    "BCCBTC":  0.001,
    "MCOBTC":  0.01,
    "WTCBTC":  1,
    "QTUMBTC": 0.01,
    "OMGBTC":  0.01,
    "ZRXBTC":  1,
    "STRATBTC":0.01,
    "SNGLSBTC":1,
    "BQXBTC":  1,
    "KNCBTC":  1,
    "FUNBTC":  1,
    "SNMBTC":  1,
    "LINKBTC": 1,
    "XVGBTC":  1,
    "CTRBTC":  1,
    "SALTBTC": 0.01,
    "IOTABTC": 1,
    "MDABTC":  1,
    "MTLBTC":   1,
    "SUBBTC":   1,
    "EOSBTC":   1,
    "SNTBTC":   1,
    "ETCBTC":   0.01,
    "MTHBTC":   1,
    "ENGBTC":   1,
    "DNTBTC":   1,
    "BNTBTC":   1,
    "ASTBTC":   1,
    "DASHBTC":  0.001,
    "ICNBTC":   1,
    "OAXBTC":   1,
    "BTGBTC":   0.01,
    "EVXBTC":   1,
    "REQBTC":   1,
    "LRCBTC":   1,
    "VIBBTC":   1,
    "HSRBTC":   1,
    "TRXBTC":   1,
    "POWRBTC":  1,
    "ARKBTC":   0.01,
    "YOYOBTC":  1,
    "XRPBTC":   1,
    "MODBTC":   1,
    "ENJBTC":   1,
    "STORJBTC": 1,
    "VENBTC":   1,
    "KMDBTC":   1,
    "RCNBTC":   1,
    "NULSBTC":  1,
    "RDNBTC":   1,
    "XMRBTC":   0.001,
    "DLTBTC":   0.001,
    "AMBBTC":   0.001,
    "BATBTC":   1,
    "ZECBTC":   0.001,
    "BCPTBTC":  1,
    "ARNBTC":   1,
    "GVTBTC":   0.01,
    "CDTBTC":   1,
    "GXSBTC":   0.01,
    "POEBTC":   1,
    "QSPBTC":   1,
    "BTSBTC":   1,
    "XZCBTC":   0.01,
    "LSKBTC":   0.01,
    "TNTBTC":   1,
    "FUELBTC":  1,
    "MANABTC":  1,
    "BCDBTC":   0.001,
    "DGDBTC":   0.001,
    "ADXBTC":   1,
    "ADABTC":   1,
    "PPTBTC":   0.01,
    "CMTBTC":   1,
    "XLMBTC":   1,
    "CNDBTC":   1,
    "LENDBTC":  1,
    "WABIBTC":  1,
    "TNBBTC":   1,
    "WAVESBTC": 0.01,
    "ICXBTC":   0.01,
    "GTOBTC":   1,
    "OSTBTC":   1,
    "ELFBTC":   1,
    "AIONBTC":  1,
    "NEBLBTC":  1
}


# BASE_CURRENCY = BTC
PRECISION_BTC_NUMBER = {
    "ETHBTC":  3,
    "LTCBTC":  3,
    "BNBBTC":  0,
    "NEOBTC":  2,
    "GASBTC":  2,
    "BCCBTC":  3,
    "MCOBTC":  2,
    "WTCBTC":  0,
    "QTUMBTC": 2,
    "OMGBTC":  2,
    "ZRXBTC":  0,
    "STRATBTC": 2,
    "SNGLSBTC": 0,
    "BQXBTC":  0,
    "KNCBTC":  0,
    "FUNBTC":  0,
    "SNMBTC":  0,
    "LINKBTC": 0,
    "XVGBTC":  0,
    "CTRBTC":  0,
    "SALTBTC": 2,
    "IOTABTC": 0,
    "MDABTC":  0,
    "MTLBTC":   0,
    "SUBBTC":   0,
    "EOSBTC":   0,
    "SNTBTC":   0,
    "ETCBTC":   2,
    "MTHBTC":   0,
    "ENGBTC":   0,
    "DNTBTC":   0,
    "BNTBTC":   0,
    "ASTBTC":   0,
    "DASHBTC":  3,
    "ICNBTC":   0,
    "OAXBTC":   0,
    "BTGBTC":   2,
    "EVXBTC":   0,
    "REQBTC":   0,
    "LRCBTC":   0,
    "VIBBTC":   0,
    "HSRBTC":   0,
    "TRXBTC":   0,
    "POWRBTC":  0,
    "ARKBTC":   2,
    "YOYOBTC":  0,
    "XRPBTC":   0,
    "MODBTC":   0,
    "ENJBTC":   0,
    "STORJBTC": 0,
    "VENBTC":   0,
    "KMDBTC":   0,
    "RCNBTC":   0,
    "NULSBTC":  0,
    "RDNBTC":   0,
    "XMRBTC":   3,
    "DLTBTC":   3,
    "AMBBTC":   3,
    "BATBTC":   0,
    "ZECBTC":   3,
    "BCPTBTC":  0,
    "ARNBTC":   0,
    "GVTBTC":   2,
    "CDTBTC":   0,
    "GXSBTC":   2,
    "POEBTC":   0,
    "QSPBTC":   0,
    "BTSBTC":   0,
    "XZCBTC":   2,
    "LSKBTC":   2,
    "TNTBTC":   0,
    "FUELBTC":  0,
    "MANABTC":  0,
    "BCDBTC":   3,
    "DGDBTC":   3,
    "ADXBTC":   0,
    "ADABTC":   0,
    "PPTBTC":   2,
    "CMTBTC":   0,
    "XLMBTC":   0,
    "CNDBTC":   0,
    "LENDBTC":  0,
    "WABIBTC":  0,
    "TNBBTC":   0,
    "WAVESBTC": 2,
    "ICXBTC":   2,
    "GTOBTC":   0,
    "OSTBTC":   0,
    "ELFBTC":   0,
    "AIONBTC":  0,
    "NEBLBTC":  0
}


PRECISION_ETH_NUMBER = {
    "BNBETH": 0,
    "QTUMETH": 2,
    "SNTETH": 0,
    "BNTETH": 2,
    "EOSETH": 2,
    "OAXETH": 0,
    "DNTETH": 0,
    "MCOETH": 2,
    "ICNETH": 0,
    "WTCETH": 2,
    "OMGETH": 2,
    "ZRXETH": 0,
    "STRATETH": 2,
    "SNGLSETH": 0,
    "BXQETH": 0,
    "KNCETH": 0,
    "FUNETH": 0,
    "SNMETH": 0,
    "NEOETH": 2,
    "LINKETH": 1,
    "XVGETH": 1,
    "CTRETH": 1,
    "SALTETH": 2,
    "IOTAETH": 0,
    "MDAETH": 0,
    "MTLETH": 0,
    "SUBETH": 1,
    "ETCETH": 2,
    "MTHETH": 0,
    "ENGETH": 0,
    "ASTETH": 0,
    "DASHETH": 3,
    "BTGETH": 2,
    "EVXETH": 0,
    "REQETH": 0,
    "LRCETH": 0,
    "VIBETH": 0,
    "HSRETH": 2,
    "TRXETH": 0,
    "POWRETH": 0,
    "ARKETH": 2,
    "YOYOETH": 0,
    "XRPETH": 0,
    "MODETH": 0,
    "ENJETH": 0,
    "STORJETH": 0,
    "VENETH": 0,
    "KMDETH": 0,
    "RCNETH": 0,
    "NULSETH": 0,
    "RDNETH": 0,
    "XMRETH": 0,
    "DLTETH": 0,
    "AMBETH": 0,
    "BCCETH": 0,
    "BATETH": 0,
    "ZECETH": 3,
    "BCPTETH": 0,
    "ARNETH": 0,
    "GVTETH": 2,
    "CDTETH": 0,
    "GXSETH": 2,
    "POEETH": 0,
    "QSPETH": 0,
    "BTSETH": 0,
    "XZCETH": 0,
    "LSKETH": 0,
    "TNTETH": 0,
    "FUELETH": 0,
    "MANAETH": 0,
    "BCDETH": 3,
    "DGDETH": 3,
    "ADXETH": 0,
    "ADAETH": 0,
    "PPTETH": 0,
    "CMTETH": 0,
    "XLMETH": 0,
    "CNDETH": 0,
    "LENDETH": 0,
    "WABIETH": 0,
    "LTCETH": 3,
    "TNBETH": 0,
    "WAVESETH": 2,
    "ICXETH": 2,
    "GTOETH": 0,
    "OSTETH": 0,
    "ELFETH": 0,
    "AIONETH": 2,
    "NEBLETH": 2,
    "BRDETH": 0,
    "EDOETH": 2,
    "WINGSETH": 0,
    "NAVETH": 2,
    "LUNETH": 2,
    "TRIGETH": 2,
    "APPCETH": 0,
    "VIBEETH": 0,
    "RLCETH": 2,
    "INSETH": 2,
    "PIVXETH": 2,
    "IOSTETH": 0,
    "CHATETH": 0,
    "STEEMETH": 2,
    "NANOETH": 2,
    "VIAETH": 2,
    "BLZETH": 0,
    "AEETH": 2,
    "RPXETH": 0,
    "NCASHETH": 0,
    "POAETH": 0
}



PRECISION_USDT_NUMBER = {
    "BTCUSDT": 6,
    "ETHUSDT": 5,
    "BNBUSDT": 2,
    "BCCUSDT": 5,
    "NEOUSDT": 3,
    "LTCUSDT": 5
}

PRECISION_NUMBER = {
    CURRENCY.BITCOIN: PRECISION_BTC_NUMBER,
    CURRENCY.ETH: PRECISION_ETH_NUMBER,
    CURRENCY.USDT: PRECISION_USDT_NUMBER
}


def round_minimum_volume_by_binance_rules(volume, pair_id):
    pair_name = get_currency_pair_to_binance(pair_id)
    base_currency_id, dst_currency_id = split_currency_pairs(pair_id)
    return truncate_float(volume, PRECISION_NUMBER[base_currency_id][pair_name])


def round_volume_by_precisness_binance(pair_name, volume):
    num = PRECISION_BTC_NUMBER[pair_name]
    format_string = ".{n}f".format(n=num)

    return format(volume, format_string)
